# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e1296f82ccfa344f4a7a9e1672157a31447196d140dbb4d9df303817ff9109f7d30f1c08b988eef78b01ffbf00b2b97c57ff8d956f4042c71a2e49e45863f576

test:
  secret_key_base: c28c89daed4445f27846538f34fc2e3378351b1a7b350c02cbde9795464c63782f11e0e0120c98ace947aad3ae8ce3d7b8b3179d0e7f6f82fde3e8520449669c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
